#First App
apiVersion: v1
kind: ReplicationController
metadata:
 name: treda.test.com
spec:
 replicas: 2
 selector:
  app: firstapp
 template:
  metadata:
   labels:
    app: firstapp
  spec:
   containers:
   - name: firstcontainerapp
   image: tomcat   
   ports:
   - name: tredaport
     containerPort: 8080